# global default
container:
  image: python:3.8


lint_task:
  auto_cancellation: true
  name: "Lint: flake8"
  install_script:
    - python -m pip install --retries 3 --upgrade pip
    - pip install nox
  lint_script:
    - nox --session lint 


style_task:
  auto_cancellation: true
  name: "Format: black"
  install_script:
    - python -m pip install --retries 3 --upgrade pip
    - pip install nox
  style_script:
    - nox --session style


linux_task:
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.6"
    env:
      PY_VER: "3.7"
    env:
      PY_VER: "3.8"
  name: "Linux: ${PY_VER}"
  env:
    PATH: ${HOME}/miniconda/bin:${PATH}
  conda_cache:
    folder: ${HOME}/miniconda
    fingerprint_script:
      - wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - echo "${CIRRUS_OS} $(sha256sum miniconda.sh)"
    populate_script:
      - bash miniconda.sh -b -p ${HOME}/miniconda
      - conda config --set always_yes yes --set changeps1 no
      - conda config --set show_channel_urls True
      - conda config --add channels conda-forge
      - conda update --quiet conda
      - conda install --quiet nox pip
  check_script:
    - conda info -a
    - conda list -n base
    - conda list -n base --explicit
  nox_cache:
    folder: ${CIRRUS_WORKING_DIR}/.nox
    fingerprint_script:
      - echo "${CIRRUS_OS} tests ${PY_VER}"
      - cat ${CIRRUS_WORKING_DIR}/requirements/py$(echo ${PY_VER} | tr -d ".").yml
  test_script:
    - nox --session tests
