name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '# ✨ Congratulations! ✨ Thanks for submitting your first issue to `iris-esmf-regrid`. We really appreciate it and will get back to you as soon as possible. Awesome job 👍'
        pr-message: '# ✨ Congratulations! ✨ Thanks for submitting your first pull-request to `iris-esmf-regrid`. We really appreciate it and will get back to you as soon as possible. Awesome job 👍'
