name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '# ✨ Congratulations! ✨\nThanks for submitting your **first issue** to `iris-esmf-regrid`.\nWe really appreciate it and will get back to you as soon as possible. Awesome job 👍'
        pr-message: '# ✨ Congratulations! ✨\nThanks for submitting your **first pull-request** to `iris-esmf-regrid`.\nWe really appreciate it and will get back to you as soon as possible. Awesome job 👍'
